const char *strings[55][2] = {
    {"LUN", "MON ", },
    {"MAR", "TUE", },
    {"MER", "WED", },
    {"GIO", "THU", },
    {"VEN", "FRI", },
    {"SAB", "SAT", },
    {"DOM", "SUN", },
    {"GEN", "JEN", },
    {"FEB", "FEB", },
    {"MAR", "MAR", },
    {"APR", "APR", },
    {"MAG", "MAY", },
    {"GIU", "JUN", },
    {"LUG", "JUL", },
    {"AGO", "AUG", },
    {"SET", "SEP", },
    {"OTT", "OCT", },
    {"NOV", "NOV", },
    {"DIC", "DEC", },
    {"Problema con il dispositivo", "Problem with the device", },
    {"Errore di comunicazione", "Communication error", },
    {"Indirizzo", "Address", },
    {"Classe", "Class", },
    {"numero di serie", "serial number", },
    {"allarme di sicurezza", "safety alarm", },
    {"Impostazioni", "Settings", },
    {"Data/Ora", "Date/Time", },
    {"Lingua", "Language", },
    {"Volume", "Volume", },
    {"Luminosita'", "Brightness", },
    {"Italiano", "Italian", },
    {"Inglese", "English", },
    {"Gradi", "Degrees", },
    {"Sto ascoltando", "I'm listening", },
    {"Configuro", "Configuring", },
    {"Configura", "Configure", },
    {"Dispositivi configurati", "Configured devices", },
    {"Errore", "Error", },
    {"Errori", "Errors", },
    {"Configurazione automatica", "Automatic configuration", },
    {"Configurazione", "Configuration", },
    {"Automatica", "Automatic", },
    {"Gestisci", "Manage", },
    {"Rimuovere il dispositivo?", "Remove the device?", },
    {"Aggiungere il dispositivo?", "Add the device?", },
    {"Quanti dispositivi devono essere configurati?", "How many devices should be configured?", },
    {"Configurazione completata; se non tutti i dispositivi sono stati rilevati ripetere la procedura", "Configuration complete; if there are missing devices repeat the procedure", },
    {"Riprova", "Try again", },
    {"Dispositivi", "Devices", },
    {"Menu' assistenza", "Technical menu", },
    {"Filtri", "Filters", },
    {"Dispositivo", "Device", },
    {"Luce", "Light", },
    {"Tempo di pulizia", "Cleaning time", },
    {"Immissione", "Immission", },
};

