#ifndef AUTOGEN_FILE_STRINGS_H_INCLUDED
#define AUTOGEN_FILE_STRINGS_H_INCLUDED

typedef enum {
    STRINGS_MON = 0,
    STRINGS_TUE,
    STRINGS_WED,
    STRINGS_THU,
    STRINGS_FRI,
    STRINGS_SAT,
    STRINGS_SUN,
    STRINGS_JEN,
    STRINGS_FEB,
    STRINGS_MAR,
    STRINGS_APR,
    STRINGS_MAY,
    STRINGS_JUN,
    STRINGS_JUL,
    STRINGS_AUG,
    STRINGS_SEP,
    STRINGS_OCT,
    STRINGS_NOV,
    STRINGS_DEC,
    STRINGS_PROBLEMA_CON_IL_DISPOSITIVO,
    STRINGS_ERRORE_DI_COMUNICAZIONE,
    STRINGS_INDIRIZZO,
    STRINGS_CLASSE,
    STRINGS_NUMERO_DI_SERIE,
    STRINGS_ALLARME_DI_SICUREZZA,
    STRINGS_IMPOSTAZIONI,
    STRINGS_DATA_ORA,
    STRINGS_LINGUA,
    STRINGS_VOLUME,
    STRINGS_LUMINOSITA,
    STRINGS_ITALIANO,
    STRINGS_INGLESE,
    STRINGS_GRADI,
} strings_t;

extern const char *strings[33][2];

#endif
