const char *strings[99][2] = {
    {"LUN", "MON ", },
    {"MAR", "TUE", },
    {"MER", "WED", },
    {"GIO", "THU", },
    {"VEN", "FRI", },
    {"SAB", "SAT", },
    {"DOM", "SUN", },
    {"GEN", "JEN", },
    {"FEB", "FEB", },
    {"MAR", "MAR", },
    {"APR", "APR", },
    {"MAG", "MAY", },
    {"GIU", "JUN", },
    {"LUG", "JUL", },
    {"AGO", "AUG", },
    {"SET", "SEP", },
    {"OTT", "OCT", },
    {"NOV", "NOV", },
    {"DIC", "DEC", },
    {"Problema con il dispositivo", "Problem with the device", },
    {"Errore di comunicazione", "Communication error", },
    {"Indirizzo", "Address", },
    {"Classe", "Class", },
    {"numero di serie", "serial number", },
    {"Seriale", "Serial", },
    {"allarme di sicurezza", "safety alarm", },
    {"Impostazioni", "Settings", },
    {"Data/Ora", "Date/Time", },
    {"Lingua", "Language", },
    {"Volume", "Volume", },
    {"Luminosita'", "Brightness", },
    {"Italiano", "Italian", },
    {"Inglese", "English", },
    {"Gradi", "Degrees", },
    {"Sto ascoltando", "I'm listening", },
    {"Configuro", "Configuring", },
    {"Configura", "Configure", },
    {"Dispositivi configurati", "Configured devices", },
    {"Errore!", "Error!", },
    {"Errori", "Errors", },
    {"Configurazione automatica", "Automatic configuration", },
    {"Configurazione", "Configuration", },
    {"Automatica", "Automatic", },
    {"Gestisci", "Manage", },
    {"Rimuovere il dispositivo?", "Remove the device?", },
    {"Aggiungere il dispositivo?", "Add the device?", },
    {"Quanti dispositivi devono essere configurati?", "How many devices should be configured?", },
    {"Configurazione completata; se non tutti i dispositivi sono stati rilevati ripetere la procedura", "Configuration complete; if there are missing devices repeat the procedure", },
    {"Riprova", "Try again", },
    {"Dispositivi", "Devices", },
    {"Setup sistema", "System setup", },
    {"Sistema R.E.C.", "R.E.C. System", },
    {"Ventilazione", "Ventilation", },
    {"Filtraggio", "Filtering", },
    {"Sensori", "Sensors", },
    {"Dispositivi R.E.C.", "R.E.C. Devices", },
    {"Conf. automatica", "Automatic config", },
    {"Ricerca", "Search", },
    {"Manutenzione", "Maintenance", },
    {"Filtri attivi", "Active filtering", },
    {"Setup manutenzione", "Setup maintenance", },
    {"Pressione", "Pressure", },
    {"Umidita", "Humidity", },
    {"Temperatura", "Temperature", },
    {"Inizia cal.", "Start cal.", },
    {"Filtri", "Filters", },
    {"Dispositivo", "Device", },
    {"Luce", "Light", },
    {"Tempo di pulizia", "Cleaning time", },
    {"Immissione", "Immission", },
    {"Aspirazione", "Syphoning", },
    {"All.", "Alarm", },
    {"Gruppo", "Group", },
    {"Filtro", "Filter", },
    {"Ore lavoro", "Work hours", },
    {"Ore rimaste", "Hours left", },
    {"Versione", "Version", },
    {"Calibrazione pressione", "Pressure calibration", },
    {"Attenzione!", "Warning!", },
    {"E' necessaria la manutenzione del filtro %s; contattare l'assistenza per prenotare un appuntamento", "Maintenance of filter %s is required; contact the assistance to book the maintenance intervention", },
    {"E' necessaria la manutenzione del filtro %s; contattare l'assistenza", "Filter maintenance for %s is required; contact the assistance", },
    {"Passivo", "passive", },
    {"WiFi", "WiFi", },
    {"On", "On", },
    {"Off", "Off", },
    {"Connesso", "Connected", },
    {"Connessione in corso", "Connecting", },
    {"Non connesso", "Not connected", },
    {"Opzioni", "Options", },
    {"Reti", "Networks", },
    {"Nessuna rete trovata", "No network found", },
    {"Correnti", "Current", },
    {"Log", "log", },
    {"Accensione", "Power on", },
    {"Ok", "Ok", },
    {"E' stato rilevato un errore di sicurezza, per cui, l'impianto ha interrotto tutte le funzionalita che possono causare danni a cose e persone. CONTATTARE L'ASSISTENZA TECNICA", "A safety error has been detected, therefore, the system has interrupted all the functions that can cause damage to people and things. CONTACT TECHNICAL SUPPORT", },
    {"Si sta cercando di bypassare i sistemi di sicurezza dell'impianto. Si tratto di un operazione consentita solo ed esclusivamente a personale qualificato. Si declinano tutte le responsabilita per l'uso improprio ed incauto dell'impianto.", "An attempt is being made to bypass the plant's security systems. This is an operation permitted only and exclusively to qualified personnel. We decline all responsibility for the improper and careless use of the system.", },
    {"Reset & IP Automatico", "Reset & Auto-assign IP", },
    {"Al momento %s dispositivi stanno comunicando correttamente con il sistema. Quanti dispositivi sono collegati alla rete REC?", "Currently %s devices are communicating correctly with the system. How many devices are connected in the REC network?", },
};

